"""empty message

Revision ID: 1170a9adba44
Revises: 8ea73a663392
Create Date: 2025-08-29 14:10:01.782114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1170a9adba44'
down_revision = '8ea73a663392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonus_cards', schema=None) as batch_op:
        batch_op.alter_column('card_number',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('activated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('deactivated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('bonus_cards_card_number_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_bonus_cards_card_number'), ['card_number'], unique=True)

    with op.batch_alter_table('c_order_status', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('can_transition_to',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('c_order_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('can_transition_to',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)

    with op.batch_alter_table('bonus_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bonus_cards_card_number'))
        batch_op.create_unique_constraint(batch_op.f('bonus_cards_card_number_key'), ['card_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('deactivated_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('activated_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('card_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
