"""empty message

Revision ID: 11729d82ce06
Revises: 1170a9adba44
Create Date: 2025-08-29 15:38:28.638107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11729d82ce06'
down_revision = '1170a9adba44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        # Сначала добавляем поле как nullable
        batch_op.add_column(sa.Column('re_confirmed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_confirmed_items_locked', sa.Boolean(), nullable=True))
    
    # Заполняем существующие записи значением по умолчанию
    op.execute("UPDATE orders SET is_confirmed_items_locked = false WHERE is_confirmed_items_locked IS NULL")
    
    # Теперь делаем поле NOT NULL
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('is_confirmed_items_locked', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('is_confirmed_items_locked')
        batch_op.drop_column('re_confirmed_at')
    # ### end Alembic commands ###
