"""Add bonus_cards table

Revision ID: 42c5fa867d99
Revises: 
Create Date: 2025-07-31 11:00:34.126674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c5fa867d99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_cards',
    sa.Column('card_number', sa.String(length=6), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('client_phone', sa.Text(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_staff_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('total_saved_amount', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bonus_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bonus_cards_card_number'), ['card_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonus_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bonus_cards_card_number'))

    op.drop_table('bonus_cards')
    # ### end Alembic commands ###
