"""add bonus cards table

Revision ID: 5b8409f6c7af
Revises: 42c5fa867d99
Create Date: 2025-08-07 16:58:12.264261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b8409f6c7af'
down_revision = '42c5fa867d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonus_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_used', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_saved', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_constraint(batch_op.f('bonus_cards_created_by_staff_id_fkey'), type_='foreignkey')
        batch_op.drop_column('created_by_staff_id')
        batch_op.drop_column('client_phone')
        batch_op.drop_column('valid_until')
        batch_op.drop_column('total_saved_amount')
        batch_op.drop_column('valid_from')
        batch_op.drop_column('usage_count')
        batch_op.drop_column('notes')
        batch_op.drop_column('last_used_at')
        batch_op.drop_column('client_name')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_card_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_bonus_card_id'), ['bonus_card_id'], unique=False)
        batch_op.create_foreign_key(None, 'bonus_cards', ['bonus_card_id'], ['id'])
    
    # Обновляем существующие записи
    op.execute("UPDATE orders SET discount_amount = 0.00 WHERE discount_amount IS NULL")
    
    # Делаем колонку NOT NULL
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('discount_amount', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_bonus_card_id'))
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('bonus_card_id')

    with op.batch_alter_table('bonus_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_saved_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valid_until', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('client_phone', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by_staff_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('bonus_cards_created_by_staff_id_fkey'), 'staff', ['created_by_staff_id'], ['id'])
        batch_op.drop_column('total_saved')
        batch_op.drop_column('total_used')

    # ### end Alembic commands ###
