"""remove staff_shifts table

Revision ID: 99ebae240693
Revises: af64dd47c3f9
Create Date: 2025-08-19 11:33:40.540871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99ebae240693'
down_revision = 'af64dd47c3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала удаляем внешний ключ и колонку из table_assignments
    with op.batch_alter_table('table_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_assignments_shift_id'))
        batch_op.drop_constraint(batch_op.f('table_assignments_shift_id_fkey'), type_='foreignkey')
        batch_op.drop_column('shift_id')
    
    # Затем удаляем таблицу staff_shifts
    with op.batch_alter_table('staff_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_shifts_is_active'))
        batch_op.drop_index(batch_op.f('ix_staff_shifts_shift_date'))
        batch_op.drop_index(batch_op.f('ix_staff_shifts_staff_id'))

    op.drop_table('staff_shifts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('table_assignments_shift_id_fkey'), 'staff_shifts', ['shift_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_table_assignments_shift_id'), ['shift_id'], unique=False)

    op.create_table('staff_shifts',
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('shift_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('shift_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_orders', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_revenue', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('staff_shifts_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_shifts_pkey'))
    )
    with op.batch_alter_table('staff_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_shifts_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_shifts_shift_date'), ['shift_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_shifts_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###
