"""Add total_guests field to daily_reports table

Revision ID: c7d8e9f1a2b3
Revises: b179618f5f0e
Create Date: 2025-09-04 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d8e9f1a2b3'
down_revision = 'b179618f5f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('total_guests', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_reports', 'total_guests')
    # ### end Alembic commands ###
