"""add banners table

Revision ID: af64dd47c3f9
Revises: 5b8409f6c7af
Create Date: 2025-08-14 16:37:26.154171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af64dd47c3f9'
down_revision = '5b8409f6c7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('link_text', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banner_image_path'), ['image_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_banner_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_banner_sort_order'), ['sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_banner_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banner_title'))
        batch_op.drop_index(batch_op.f('ix_banner_sort_order'))
        batch_op.drop_index(batch_op.f('ix_banner_is_active'))
        batch_op.drop_index(batch_op.f('ix_banner_image_path'))

    op.drop_table('banner')
    # ### end Alembic commands ###
